SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;

SELECT MAX(QUANTITY) AS MAX_QUANT FROM PETRESCUE;

SELECT AVG(COST) AS AVG_COST FROM PETRESCUE;

SELECT AVG(COST/QUANTITY) AS AVG_DOG_COST FROM PETRESCUE
WHERE UCASE(ANIMAL) LIKE '%DOG%';

SELECT TC/TA as DOG_AVG
FROM (SELECT SUM(QUANTITY) AS TA, SUM(COST) AS TC
	  FROM PETRESCUE WHERE ANIMAL='Dog');

SELECT ROUND(COST) AS ROUND_COST FROM PETRESCUE;

SELECT LENGTH(ANIMAL) AS L_NAME FROM PETRESCUE;

SELECT UCASE(ANIMAL) AS ANIMAL FROM PETRESCUE;

SELECT DISTINCT(UCASE(ANIMAL)) AS ANIMAL FROM PETRESCUE;

SELECT * FROM PETRESCUE
WHERE LCASE(ANIMAL) LIKE '%cat%';

SELECT DAY(RESCUEDATE) AS DAY FROM PETRESCUE
WHERE ANIMAL='Cat'; 

SELECT SUM(QUANTITY) AS MAY_RESCUES FROM PETRESCUE 
WHERE MONTH(RESCUEDATE)='05';

SELECT SUM(QUANTITY) AS RESCUES_14 FROM PETRESCUE
WHERE DAY(RESCUEDATE)='14';

SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE;

SELECT CURRENT_DATE-RESCUEDATE AS DSR FROM PETRESCUE; 